import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

/**
 * RTL DISCIPLINE GUARD
 * ---------------------------------------------------------------------------
 * This site is Arabic-first (dir="rtl"). Physical-direction Tailwind classes
 * look correct to an English-reading developer and are mirrored-wrong for
 * every real user. Use logical properties instead:
 *
 *   ml-/mr-      -> ms-/me-
 *   pl-/pr-      -> ps-/pe-
 *   left-/right- -> start-/end-
 *   text-left/right -> text-start/text-end
 *   border-l/r-  -> border-s/e-
 *   rounded-l/r- -> rounded-s/e-
 *
 * Deliberately a WARNING, not an error: a handful of elements genuinely must
 * not mirror (e.g. an embedded LTR map control, a Latin wordmark). Those are
 * rare — if you are silencing this more than a couple of times per file, you
 * are almost certainly doing it wrong. Silence with an inline
 * `// eslint-disable-next-line no-restricted-syntax` plus a one-line reason.
 */
const RTL_PHYSICAL_CLASS =
  /(^|\s)-?(ml|mr|pl|pr|border-l|border-r|rounded-l|rounded-r|rounded-tl|rounded-tr|rounded-bl|rounded-br|left|right|float-left|float-right|text-left|text-right|origin-left|origin-right)(-|$|\s)/;

const rtlGuard = {
  selector: `JSXAttribute[name.name='className'] Literal[value=${RTL_PHYSICAL_CLASS}]`,
  message:
    "RTL: physical-direction class detected. Use logical properties (ms-/me-/ps-/pe-/start-/end-/text-start/text-end/border-s-/border-e-/rounded-s-/rounded-e-) so the layout mirrors in Arabic.",
};

const rtlGuardTemplate = {
  selector: `JSXAttribute[name.name='className'] TemplateElement[value.raw=${RTL_PHYSICAL_CLASS}]`,
  message: rtlGuard.message,
};

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    files: ["src/**/*.{ts,tsx}"],
    // shadcn/Magic UI components are vendored copies from upstream registries.
    // We do not police their internals — CYPHER converts them deliberately.
    ignores: ["src/components/ui/**"],
    rules: {
      "no-restricted-syntax": ["warn", rtlGuard, rtlGuardTemplate],
    },
  },
  {
    // Vendored registry code (shadcn / Magic UI). These files are copied in
    // verbatim and are re-generated by `shadcn add`, so hand-fixes get lost.
    //
    // `react-hooks/set-state-in-effect` (new in eslint-plugin-react-hooks v7)
    // fires on shadcn's own carousel.tsx, which syncs initial state from Embla
    // — an external store — inside an effect. That is the intended pattern for
    // that rule's "subscribe to an external system" carve-out, but the rule
    // cannot see it. Scoped off here rather than globally.
    files: ["src/components/ui/**/*.{ts,tsx}"],
    rules: {
      "react-hooks/set-state-in-effect": "off",
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
  ]),
]);

export default eslintConfig;
