import * as React from "react";
import Image from "next/image";

import {
  type Fact,
  type MediaFact,
  factHref,
  factText,
  isMediaResolved,
  isResolved,
  isTestData,
} from "@/content/placeholders";
import { cn } from "@/lib/utils";

/* -----------------------------------------------------------------------------
 * <FactText> / <FactLink> — the ONLY sanctioned way to put a client-supplied
 * fact on the page.
 *
 * Why a component and not just a string:
 *
 *   1. It is impossible to accidentally render a fake value. These read
 *      `fact.value` through `factText()`, which returns the honest Arabic
 *      fallback (`يُضاف رقم الترخيص`) whenever the client has not supplied one.
 *      Nothing else in the codebase reads `.value`.
 *
 *   2. It is impossible to accidentally render a dead link. `factHref()`
 *      returns null while a fact is pending, and <FactLink> then renders TEXT.
 *      A phone number that does not exist can never become `tel:undefined`.
 *
 *   3. Every pending fact is greppable in the built HTML:
 *          grep -o 'data-pending' out/index.html | wc -l
 *      and every one names itself via `data-fact="contact.phone"`. That is the
 *      launch checklist, generated by the page itself.
 *
 * Pending values render in `--fg-subtle` — quieter than real content, still
 * comfortably AA on every ground (6.16:1 at worst, see /styleguide). They are
 * not hidden: a visitor should be able to see that the association has not
 * published its licence number yet. That is the honest state of the world.
 *
 *   4. ⛔ A RESOLVED FACT CAN STILL BE A FAKE ONE, and guarantee 3 above does
 *      not catch that — `data-pending` disappears the instant `value` is set,
 *      whoever set it and whatever they set it to. So a fact carrying
 *      `testData` (see the field's own block in placeholders.ts) also stamps
 *      `data-test-data` here, holding the value it is showing. That makes
 *
 *          grep -o 'data-test-data' out/index.html
 *
 *      the launch gate that `grep data-pending` cannot be: it must find
 *      NOTHING before this site is published as the association's own.
 *      `testDataFacts()` is the same audit at build time.
 *
 *      It is a DOM marker, not a visual one. The page looks exactly the same
 *      with or without it — marking a test value in the interface would be
 *      telling a visitor about our data pipeline. Whose job it is to notice is
 *      the operator's, and the operator reads the DOM and the source, not the
 *      rendered page.
 *
 * Server Components — no interactivity, no hooks.
 * -------------------------------------------------------------------------- */

export interface FactTextProps extends React.ComponentProps<"span"> {
  fact: Fact;
  /**
   * Direction for the isolated value, when `dir="auto"` is not good enough.
   *
   * `<bdi>` resolves `auto` from the first STRONG character, and a value that
   * has none — `+963934826796` is a `+` and nine digits, all weak — falls back
   * to the base direction. Pass `"ltr"` on a phone number, an email address or
   * a URL and the run is both isolated and explicitly Latin-ordered
   * (SOVA §16.8). Leave it off for anything that starts with an Arabic letter.
   */
  valueDir?: "ltr" | "rtl" | "auto";
}

export function FactText({ fact, valueDir, className, ...props }: FactTextProps) {
  const resolved = isResolved(fact);
  const value = factText(fact);

  return (
    <span
      data-fact={fact.id}
      data-pending={resolved ? undefined : ""}
      /* ⛔ See guarantee 4 at the top of this file. Only ever set while a
         value the association did not supply is on screen. */
      data-test-data={isTestData(fact) ? value : undefined}
      className={cn(!resolved && "text-fg-subtle", className)}
      {...props}
    >
      {/* ALWAYS ISOLATED (SOVA §16.8) — CYPHER.
          Mixed Arabic/Latin runs reorder unpredictably, and this component is
          the seam through which every client-supplied value enters the page.
          It used to isolate only when `fact.protocol != null`, i.e. only the
          phone/email/WhatsApp/document facts — which left the licence number,
          the office address, the opening hours, the travel times and the whole
          commercial block un-isolated the moment the client fills them in.
          Those are exactly the strings that carry digits, slashes, dates and
          `كم`/`م²` next to Arabic, and several of them render INLINE beside an
          Arabic label (`documents.*` in the footer list, `contact.delivery` in
          the form notice) where the reordering is visible.
          A <bdi> around a pure-Arabic fallback costs nothing: `dir="auto"`
          resolves it to RTL, the same base direction it already had. Verified
          in a browser — isolating every fact slot moved no glyph on the page. */}
      {/* `valueDir` only applies to a REAL value: the fallback is a pure
          Arabic sentence and forcing it LTR would push its full stop to the
          wrong end. */}
      <bdi dir={resolved ? valueDir : undefined}>{value}</bdi>
    </span>
  );
}

export interface FactLinkProps extends Omit<React.ComponentProps<"a">, "href"> {
  fact: Fact;
  /** See <FactText>. Applies to the link text once the fact resolves. */
  valueDir?: "ltr" | "rtl" | "auto";
}

/**
 * Renders an <a> once the fact is real, and plain text until then. There is no
 * third state — we never ship a link that goes nowhere, and never a `#` href
 * standing in for a phone number (which is exactly what the old site's
 * WhatsApp button did: `href="#contact"` with a comment apologising for it).
 */
export function FactLink({ fact, valueDir, className, ...props }: FactLinkProps) {
  const href = factHref(fact);

  if (!href) {
    return <FactText fact={fact} valueDir={valueDir} className={className} />;
  }

  return (
    <a
      href={href}
      data-fact={fact.id}
      data-test-data={isTestData(fact) ? fact.value : undefined}
      className={cn(
        "hover:text-fg underline decoration-line-strong decoration-1 underline-offset-[6px] transition-colors hover:decoration-current",
        className,
      )}
      {...props}
    >
      <bdi dir={valueDir}>{factText(fact)}</bdi>
    </a>
  );
}

export interface FactMediaProps extends Omit<React.ComponentProps<"div">, "children"> {
  fact: MediaFact;
  /** `sizes` for the real image. Required once the asset lands — pass it now. */
  sizes: string;
  /** The caller owns the aspect box (`aspect-[4/3] w-full`, a fixed height…). */
  className?: string;
  /**
   * OPTIONAL art behind the pending sentence. Added 2026-08-22 for `/board`,
   * where five empty frames in a row read as a broken page rather than as an
   * honest one.
   *
   * ⛔ IT DOES NOT REPLACE THE SENTENCE AND MUST NOT BE ALLOWED TO. The
   * fallback text still renders on top of it, still carries `data-pending`,
   * and is still what a screen reader reaches — this is a watermark UNDER an
   * unchanged empty state, not a way to make a gap look filled. Anything
   * passed here has to read as deliberately blank at a glance; a stock
   * photograph or an avatar of a person is exactly what it is for NOT.
   */
  placeholder?: React.ReactNode;
}

/**
 * The MediaFact counterpart of <FactText> — WAVE 2.
 *
 * Same contract, same guarantees: nothing else in the codebase reads
 * `MediaFact.src`, an unsupplied asset renders its honest Arabic fallback
 * instead of a broken <img>, and the slot carries `data-fact` + `data-pending`
 * so `grep data-pending` over a built page still audits the whole site.
 *
 * The empty state is deliberately a plain framed slot with a sentence in it,
 * not an icon, not a dashed box, not a skeleton shimmer. A shimmer implies
 * something is loading; nothing is loading. A photograph does not exist.
 */
export function FactMedia({
  fact,
  sizes,
  className,
  placeholder,
  ...props
}: FactMediaProps) {
  const resolved = isMediaResolved(fact);

  return (
    <div
      data-fact={fact.id}
      data-pending={resolved ? undefined : ""}
      className={cn("bg-veil-05 relative overflow-hidden", className)}
      {...props}
    >
      {resolved ? (
        <Image
          src={fact.src}
          alt={fact.alt}
          fill
          sizes={sizes}
          className="object-cover"
        />
      ) : (
        <>
          {placeholder}
          <span className="text-body-sm text-fg-subtle absolute inset-0 flex items-center justify-center p-8 text-center text-balance">
            {fact.fallback}
          </span>
        </>
      )}
    </div>
  );
}
