import type { Metadata, Viewport } from "next";
import {
  Alexandria,
  IBM_Plex_Sans_Arabic,
  Noto_Naskh_Arabic,
} from "next/font/google";

import { SiteFooter } from "@/components/layout/site-footer";
import { SiteHeader } from "@/components/layout/site-header";
import { SmoothScrollMount } from "@/components/motion/smooth-scroll-mount";
import { DirectionProvider } from "@/components/ui/direction";
import { site } from "@/content/site";
import { siteUrl } from "@/lib/site-url";

import "./globals.css";

/* -----------------------------------------------------------------------------
 * Fonts — Arabic-first.
 * Each family is exposed as a CSS variable on <html>; Tailwind maps them to
 * font-display / font-body / font-naskh in globals.css (@theme inline).
 *
 * Do NOT add `weight` to a variable font (Alexandria, Noto Naskh Arabic) —
 * omitting it pulls the full variable axis, which is smaller than several
 * static cuts. IBM Plex Sans Arabic has no variable build, so weights are
 * enumerated explicitly.
 * -------------------------------------------------------------------------- */

const fontDisplay = Alexandria({
  variable: "--font-display",
  subsets: ["arabic", "latin"],
  display: "swap",
});

const fontBody = IBM_Plex_Sans_Arabic({
  variable: "--font-body",
  subsets: ["arabic", "latin"],
  // ASTRA: trimmed from 300-700. The type system uses exactly three weights
  // (400 body, 500, 600 labels/headings-in-body-face); Arabic cannot use
  // uppercase for hierarchy, so weight does that job and only these three are
  // needed. Two fewer static cuts on every page load.
  weight: ["400", "500", "600"],
  display: "swap",
});

// Wired up but intentionally NOT applied globally. Reach for `font-naskh` only
// on editorial / quotation moments (e.g. the president's message).
//
// ⛔ `preload: false` — SAGE, and it is not an optimisation, it is a
// correction. MEASURED with a cold cache: this family's arabic subset is
// 92.1 KB, the single largest asset on the site after the hero photograph, and
// `next/font` was emitting `<link rel="preload">` for it from the ROOT layout —
// so every route paid for it. `/privacy` and all six `/projects/[slug]` pages
// downloaded 92.1 KB (+15.0 KB latin) of Noto Naskh to render EXACTLY ZERO
// characters in it. Verified: the only two elements on the whole site with
// `font-naskh` are the bismillah and the quote, both inside `#president`.
//
// With preload off the @font-face and the CSS variable are unchanged; the
// browser simply fetches the file when an element actually needs it. `/` still
// gets it (the president's section is on it) but off the critical path, and
// the routes that never use it no longer request it at all.
//
// If Naskh is ever promoted to a second section, re-measure before re-adding
// the preload — AGENTS §2 says it is an accent face, and this is what that
// costs when it is treated as a global one.
const fontNaskh = Noto_Naskh_Arabic({
  variable: "--font-naskh",
  subsets: ["arabic", "latin"],
  display: "swap",
  preload: false,
});

/* -----------------------------------------------------------------------------
 * Metadata. Every user-facing string comes from src/content/site.ts, so the
 * <title> and the OG card cannot drift from the copy on the page.
 *
 * NOTE: the scaffold shipped `جمعية البنيان السكنية`; the client's own name — and
 * every occurrence of it on the live site — is `جمعية البنيان السكنية`, with the
 * definite article (SOVA §5.1). Corrected here to the verbatim source.
 *
 * WAVE 3 closed SOVA §9 #15/#16:
 *   · the favicon and the apple icon are generated from <AnkaaMark />'s own
 *     traced path data — `src/app/icon.tsx`, `apple-icon.tsx`
 *   · the OG/Twitter card is generated by `next/og` from the brand alone and
 *     makes no claim — `src/app/opengraph-image.tsx`. `og:image` is injected
 *     from that file convention, which is why `openGraph.images` is absent
 *     below rather than hand-written.
 *   · `Organization` / `WebSite` / `FAQPage` JSON-LD is emitted from
 *     `src/components/seo/json-ld.tsx`, with every unresolved fact OMITTED.
 *
 * ⚠ `metadataBase` is only as correct as `NEXT_PUBLIC_SITE_URL`. Wave 1's
 * `https://ankaa.sy` fallback was a guessed domain and is gone; the fallback is
 * now a reserved `.example` origin that cannot belong to anyone. See
 * `src/lib/site-url.ts` and `.env.example`.
 * -------------------------------------------------------------------------- */
export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: site.meta.title,
    template: `%s | ${site.meta.title}`,
  },
  description: site.meta.description,
  applicationName: site.meta.title,
  keywords: [
    "جمعية البنيان السكنية",
    "البنيان السكنية",
    "مشاريع سكنية تعاونية",
    "جمعية سكنية مرخصة",
    "ريف دمشق الغربي",
    "الانتساب",
  ],
  openGraph: {
    type: "website",
    locale: site.meta.locale,
    url: siteUrl,
    siteName: site.meta.title,
    title: site.meta.title,
    description: site.meta.description,
  },
  twitter: {
    card: "summary_large_image",
    title: site.meta.title,
    description: site.meta.description,
  },
  robots: { index: true, follow: true },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#fbfaf6" },
    { media: "(prefers-color-scheme: dark)", color: "#002724" },
  ],
};

/* -----------------------------------------------------------------------------
 * `modal` is the @modal PARALLEL SLOT (src/app/@modal/). It renders alongside
 * `children`, not instead of it — which is exactly what a project overlay is:
 * the home page stays mounted and scrolled behind it, and Radix can therefore
 * restore focus to the card that opened it. On every route without an
 * intercepted match the slot renders `@modal/default.tsx`, i.e. null.
 * -------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
 * THE INTRO GUARD — NEON. SOVA §17's `sessionStorage` guard, as a blocking
 * inline script rather than a React effect.
 *
 * WHY IT CANNOT BE AN EFFECT. The hero's resting state is the FINISHED hero
 * (base state = final state). An intro started from `useEffect` would paint the
 * assembled hero, then cover it with paper, then reveal it again — the visitor
 * sees the ending first. This runs before the first paint and puts the document
 * into step 1 of the sequence; the two CSS rules it activates are in
 * globals.css §8.1 and the timeline that reads it is `hero-motion.tsx`.
 *
 * It decides, and only decides:
 *   · reduced motion  → never run
 *   · otherwise → `data-ankaa-intro="run"`, plus a 6s failsafe that clears it
 *     even if the bundle never loads. A visitor must never be stranded on a
 *     blank cream page because a script 404'd.
 *
 * ⭐ N2 — ITS MEMORY IS THE DOCUMENT, AND THAT IS THE WHOLE OF THE CHANGE.
 *
 * There used to be a third condition: a `sessionStorage["ankaa-intro"]` flag
 * that made the sequence once-per-tab. The operator wants it on every refresh,
 * so the flag is gone and nothing replaced it — **being an inline script IS the
 * guard now.** This tag is executed exactly once per DOCUMENT: a full load
 * runs it, and a client-side navigation does not re-execute an inline
 * `<script>`, so the App Router moving between `/` and `/privacy` cannot
 * replay the intro no matter how many times it re-renders this layout.
 *
 * The other three conditions are untouched, deliberately: reduced motion still
 * never runs it, the 6s failsafe is still here, and the 4s flicker timeout
 * below is still armed before anything that could throw.
 *
 * ⚠ ONE KNOWN EDGE, unchanged by N2 and recorded so it is not rediscovered as
 * a regression: this script cannot tell which route it is on (see BRIMSTONE in
 * globals.css §8.1), so a hard load of `/privacy` also sets the attribute, and
 * a client-side navigation to `/` inside the following 6 seconds finds it still
 * set and plays the intro. `<HeroMotion>` only mounts on `/`, which is why
 * nothing clears it earlier there. It behaved identically before.
 *
 * ⭐ THE 4s FLICKER TIMEOUT — the third escape for globals.css §8.3.
 *
 * It was 1.8s until 2026-10-04. Measured on a cold cache: the bundle lands at
 * ~2.4s on 4G and ~5.2s on slow 4G, so 1.8s declared almost every FIRST visit
 * "late" and skipped the intro — it only ever played on a refresh. 4s was the
 * operator's call: the intro plays on normal mobile/VPN first visits, and a
 * slow link still gets the page well inside the 6s failsafe.
 *
 * §8.3 pre-hides six elements and had exactly two escapes: `(scripting: none)`
 * and `(prefers-reduced-motion: reduce)`. FADE measured what neither of them
 * covers — scripting ENABLED but the bundle late or absent:
 *
 *   Slow 3G          hero blank 22.0s (all five nodes `visibility:hidden`
 *                    at 1s, 3s AND 8s — a bare green rectangle and a logo)
 *   one JS chunk 404 hero blank FOREVER, `<h1>` occupying 297px, invisible
 *
 * So the FIRST thing this script does — before the try/catch has anything it
 * could throw on, and from inline HTML that no chunk failure can take away —
 * is arm a 4s timer. 4s, not 6s: this is a deadline for the BUNDLE, not
 * for the intro, and a visitor staring at an empty hero counts the seconds.
 *
 * ⛔ THE TIMER IS NOT UNCONDITIONAL, AND THAT IS THE WHOLE DESIGN.
 * `<HeroMotion>` stamps `data-ankaa-motion` on `<html>` the instant its layout
 * effect runs. The timer fires, finds that attribute, and does nothing — so a
 * normal visit is byte-for-byte the intro that was always there. It only acts
 * when motion has NOT arrived by 4s, and then it does two things:
 *
 *   `data-flicker-timeout`  → globals.css §8.3 reveals the pre-hidden type
 *   removes `data-ankaa-intro` → §8.1 drops the paper and releases the header,
 *                             which otherwise stay in step 1 of a sequence
 *                             that has no code to run it, until the 6s failsafe
 *
 * The 6s failsafe stays. It is now the second line of defence rather than the
 * first, and it is what covers the case where the timer itself is starved.
 *
 * `hero-motion.tsx` reads `data-flicker-timeout` and, if it finds it, skips its
 * entrance tweens and jumps to the resting state — content that has already
 * been on screen for two seconds must not be faded in from zero.
 *
 * ⭐ AND IT TURNS OFF THE BROWSER'S SCROLL RESTORATION — VIPER V-2.
 *
 * `<ScrollRestoration>` in `smooth-scroll.tsx` owns restoration, and it cannot
 * set this flag itself: it arrives in a deferred chunk, and by then the browser
 * has ALREADY restored. Measured — reload a project overlay and the browser put
 * the short page at `scrollY === maxY === 1011`, because the position it had
 * stored was the home page's 2,851 behind the modal. One line, here, is the
 * only place early enough to prevent it.
 *
 * ⛔ THE TWO HALVES ARE ONE FIX. If `<ScrollRestoration>` is ever removed,
 * REMOVE THIS TOO — a document with `manual` restoration and nobody restoring
 * it opens at the top after every reload and every Back.
 *
 * ⭐ AND WHERE THE INTRO STARTS IS NOT DECIDED HERE — N6.
 *
 * This script decides WHETHER the sequence runs. `hero-motion.tsx` decides
 * WHEN: it holds the first frame until the fonts have loaded and the hero
 * photograph has decoded, capped so nothing can start later than 1.5s after
 * navigation start. Splitting it that way is what keeps the 4s timer below
 * meaningful — the gate never delays `data-ankaa-motion`, which is stamped
 * synchronously before any waiting begins. Read `hero-motion.tsx`'s READINESS
 * GATE block before changing either number.
 *
 * It is ~380 bytes. The try/catch is belt-and-braces for a script that runs
 * before anything else in the document and has no error boundary above it; the
 * 4s timer is armed on the first line inside it so that even a throw on the
 * next statement cannot take the flicker escape away.
 * -------------------------------------------------------------------------- */
const INTRO_GUARD = `try{var d=document.documentElement;if("scrollRestoration"in history)history.scrollRestoration="manual";setTimeout(function(){if(!d.hasAttribute("data-ankaa-motion")){d.setAttribute("data-flicker-timeout","");d.removeAttribute("data-ankaa-intro")}},4000);if(!matchMedia("(prefers-reduced-motion: reduce)").matches){d.setAttribute("data-ankaa-intro","run");setTimeout(function(){d.removeAttribute("data-ankaa-intro")},6000)}}catch(e){}`;

export default function RootLayout({ children, modal }: LayoutProps<"/">) {
  return (
    // lang="ar" + dir="rtl" from commit 1 — the whole document mirrors,
    // and every logical utility (ms-/me-/ps-/pe-/start-/end-) resolves correctly.
    <html
      lang="ar"
      dir="rtl"
      className={`${fontDisplay.variable} ${fontBody.variable} ${fontNaskh.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        {/* First thing in the document, before anything paints. See above. */}
        <script dangerouslySetInnerHTML={{ __html: INTRO_GUARD }} />

        {/* Radix primitives need the direction in context too, otherwise
            popovers/menus/carousels compute their side/align against LTR. */}
        <DirectionProvider dir="rtl">
          {/* Lenis + the GSAP ticker handshake, plus the scroll restorer.
              ⛔ IT IS A SIBLING, NOT A WRAPPER, AND IT IS DEFERRED. It used to
              wrap everything below, which put gsap + ScrollTrigger + lenis —
              336KB, ~35% of the 404's JavaScript — into the shared chunk group
              of every route (CHAMBER C2-1). It renders no DOM either way.
              `smooth-scroll-mount.tsx` holds the `ssr: false` boundary that a
              Server Component cannot declare itself; `smooth-scroll.tsx` has
              the rest of the reasoning. Under `prefers-reduced-motion` it
              mounts and does nothing, and the browser's own scrolling is used
              (SOVA §15.4). */}
          <SmoothScrollMount />

          {/* The shell wraps every route: fixed header over the hero, footer
              floor. `main` is rendered by the page and carries id="main" for
              the header's skip link. */}
          <SiteHeader />
          {children}
          {modal}
          <SiteFooter />
          {/* ⛔ NO <Toaster /> — SAGE. It was mounted here and `toast()` is
              never called anywhere in the codebase (`grep -rn "toast(" src/`
              returns only this import). What it actually shipped, on every
              route, was an empty `<section aria-label="Notifications alt+T"
              aria-live="polite">`: an ENGLISH-labelled landmark AND a live
              region inside a `lang="ar"` document, announced by every screen
              reader that enumerates landmarks, for a feature that does not
              exist. The contact form has its own `role="status"` region and
              needs nothing from sonner.

              `src/components/ui/sonner.tsx` is left in place, and the reason
              now lives in that file too — if toasts are ever wanted, re-adding
              is this one line plus an Arabic label. Do not re-add it "just in
              case". */}
        </DirectionProvider>
      </body>
    </html>
  );
}
